[[Luna]]
arch = "aarch64"
git-tree-sha1 = "0b61e5e8a464f7f32888a2264c303116b33f6751"
os = "macos"

    [[Luna.download]]
    sha256 = "d45b81eac055e6581c38946722ef21c9b7cdce9dea0010c403e6e129ff96d890"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.aarch64-apple-darwin.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b6fa48afa6f1fe7b1f7b0bea04122cc01586858"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "c8dfec4350aee81f9787a8cc0a6f5c5b3afd55f09c545c1f85b197a8edf5acde"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "974db41ccf729267f5a21947d398c7ce443cd806"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "939a892a6a5925233f6fd7e6524c54f444590abae819038852d7b516fbb25429"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44a8fe151060eb7500000958ec874828b983dd68"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "d80086b8bd1f4fc3b291353790de2a8c87b4decfae443c4bb6153a1fa2c43aaa"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.aarch64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aea6d6891813158118cab19c80c0a9944a5a1275"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "2b205fbee87f11913da686413a256531d891375ac607d85eb2cf6a8e1899a326"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.aarch64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d6db604b0454676411b524df21542a3569eabff"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "f68c802192629f8139092ced3450e6f9d8021f28f5f56fc1c5de87b86d95ccb9"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4e25e61cb00d838fb2a6b2902beffbbba020df8"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "ba19b8a466d6c2b2caa335fd14deb8b4055ab43a0334ccbd8f835db74a199f21"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34f60e1d4c7a481bc8d8e673f49ac294a17a182a"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "342a2cdf4d5c0c3002f4a790e071519e76b973b5149d3f4fba1ecce19f7cc360"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e69e43b1795688af821587eaf52e5ac75965a8cc"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "8ae6b5650a8e1aec75497b0a3cc3d032ffe44c14370698018fe09149f8d67c0b"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39fcc5b38884b31ce92c9b2268ebee4c7d2031a3"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "a2f3fe994fb1fcb5a2e75624236c37db5533b9438e5ca13a9149e02f1d005cc9"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c0e3a6fa3cb8e0cec34a58917e524265d01adb2"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "8094efc0caeff745d8305547de31fe15ee50d56b08208d0f949223bbb8f4c42f"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "655dff943b9c965070b2ab907d1b697eb6be219a"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "63dd47204907f97854c10d248ce45a03762105a7be11eb21bd5bc6921fe0713b"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc2af95ef0c122f4d83b400022c040ddb7e9043c"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "46b3febc9b3178f3124a211a2105b86642b99674e6ab47bcfd5655043891e225"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae6dc50f3fba555b6ea5592c46448ce3545523c1"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "52e7e15c00471d18009070227bbadd62fc1315210be75a5769a6fb3a41ad1827"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abb7fe777809c5fc2b35c6b8bad98695ca76c5cd"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "aec656682bc03c1937f3210f332b0485d1ec6f304707107acf7cbd285477c160"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "371596d65b2b06aefabe6a5ebc4823d68385d306"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "e03de3b6a1038a1d5343ad7cdc129e3a869f5f7c465d434009f3ff9b05a9e5a4"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec2312ace7f48d761a34f4a3dad41ac4f912c8d5"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "ed7900c3d0c39848879d90a0bf7839f0dcbe46f47bfe5a0e07b0ae882986f145"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ee019fb2ca73eb2578de00582d9a3979fe01433"
os = "windows"

    [[Luna.download]]
    sha256 = "251663db9105f5dee2fb51378174238b9bb336d50310ba2799adacd4fe2c87a0"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8755beacb29ec8a6d81842b7f64b58bf429757aa"
os = "windows"

    [[Luna.download]]
    sha256 = "3f3aa252947c538ec6eefe4e8caf897206444a450fb58b8a7ff564e406af2b56"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.i686-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7df28c3e3e66d5fe233d02fb7906bddf7a6cb2c"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "69088abaf4a94defe86e69579320dceb707a2cc8da9db36ca536bc52daf31490"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92cb55ba297533cc5f80a5a4b8c0b26e5779545c"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "1ef0660df42b2fafb8769a9989d02c4888df51dfffc02564c30c932c471ad56d"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
git-tree-sha1 = "cb57195770db9e96cc81c37500bb85010f6dced6"
os = "macos"

    [[Luna.download]]
    sha256 = "aac18666931219e55e7c8a6a36158c00049b86a7c27214629ae6254784291969"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-apple-darwin.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c42ed0a2b0f059c4e821e8331df2d7e5c15b5c5"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "b8f71c211d6abc0eff79c223c70b797b8f6c5c66a449fbfb295b818be14b088c"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6f6897668ff5be92106f9ce7d28084f18b62c29"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "364480b7c7bf5609761929438601c665f41276ac3bcfe4681a4aea5a41cceff1"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25ca7ca44cd3759afbffad31671212704d66d938"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "dba913a879afa2e4d321fc24e149b3e75124aece24bb61dd8b35684a4b144fe4"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7935dcb85cac18c1c8a25d95238ebf9e696fd393"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "9f3f8a1c2f6c52629fea34ce51792a1ea03bbd2e4c1e49837abad9033eb57694"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
git-tree-sha1 = "92e5f18165b297ffffab5d702acd6b5ecc046261"
os = "freebsd"

    [[Luna.download]]
    sha256 = "8fa2ef27a4f420ed9f7e7b94c4a9b6dc25081a014539f5ef19bdc68455c9638a"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-unknown-freebsd.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c96d3843d374db9ef550ee9ee87a6d955aa2f6bb"
os = "windows"

    [[Luna.download]]
    sha256 = "10a4b4b0069739095944430033e7bc66068ff24ef30d219d3232a5baf48d8e23"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a7e6a16e29aa1919a8ec04706c06b348fa10a71"
os = "windows"

    [[Luna.download]]
    sha256 = "dff2edc633449d4086871612cfa4f18ec3acedcc018581363f7971f4f96df6f4"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.28.0+0/Luna.v0.28.0.x86_64-w64-mingw32-cxx11.tar.gz"
