[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a85ab47a6badccce0cdc8803c3dd9eb5cba65a"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "9d322d724e464fb455b61363cab4a67eec9bad8b9e987cbf2907e604c587f577"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbf908d7eff9ee1054e793ed8c0e2923688c93ef"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "42c0d4a2f3ab05f24d76d5727f3759aa0a87e1d2b606b7fb81688993aa9da9e6"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99b38d0f6a80cf4a9fbae23fbabfe84cc00f1237"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "ab52741b97c9ea5d00536768ed370e3ea31a284ad044a8b8f2cfcf374fa2268e"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b75849ece0557801ef7ac28d28e4001c16315c7e"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "7ed550d9c6f432172d29f7440eb861899d92b213588e3b9d49e6b8982b411904"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "183f95dd6b72eb2b2d3d3832e222a9a72a04e5dd"
os = "macos"

    [[Luna.download]]
    sha256 = "fce82f5aabdfe1be1b0909b57b9b217f38a122a2d98bda56c8988e1888b82cad"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3a4f30eb268e0cf85dd57ccd53c0398e56c3695"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "fc96c280510ba0fdd67e5dafbe67aa5f7061c05ad537a308ee61d441554dccf2"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a454fbd7b7b8c1d5c931c6814e954b4fc34ffbe5"
os = "windows"

    [[Luna.download]]
    sha256 = "3a5cdbef6b16253341c5e15a855262e88be14120622a7da7d66643fe1cb01bac"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d8583c20268b36c9c0963aaeb3b38e261694515"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "2d7ec9a93199dc567bb98a173e5c4d638152b80033577f7c618ea6d33206425c"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37d9431f6fd1422444312e3f2f56b45d26584355"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "787b35c9d9b4314479238dd46fae28c3a9b2f0e4f997cc7586a4b8fb58b39b59"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.aarch64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35eea162477c9a46d1af6736a0e06ca093e0f38d"
os = "macos"

    [[Luna.download]]
    sha256 = "fa7afcae0691d6b423f9a8fddefa068119b556d295099db2313fd21a2680f627"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83706562d5b921451ec19ef2154ade586648a37c"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "1d4ad90a46aafdcdaf255c6c17beb3cb11472a58c9b3c982068575acb9df77d1"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d279887ac982cebf85f4842d3880b73a970bddb5"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "34db99b18df677d58e1d622e1f19e7411d093db1beda702b09936fb119b42487"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ebcc41587557c0f4362a28f83d33fdb51d845cc"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "835a3e1db1d5f4215881c1f5de190229311c9e88cb108da3e845ac83c100c383"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d1d58034bb74c79f856a3243e7774af64da5c8b"
os = "freebsd"

    [[Luna.download]]
    sha256 = "78ec08cd0374faf5cdfab1c6612a2e84f3518b0153ae42ea853354bc0adf578a"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af9feec21415d2745f7497835e89b74a1b306105"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "bc0b574d4c877ed8fd75a780389b4ed8b2ec5b2191607d82a80fc90cd2ddcb9d"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e00564fb9f7f2a703208325b08bfa2d454d8b93a"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "db50f2828c472716a07eb5012f4dd4a6750f7700fbb13b4b685602dd4fb15e52"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76c058c795ffb7f76bd460e8aa2aa80d99cc73ce"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "5edc203181400dc3f1171da552bbb75c670c2716fae2a57608753b3048384ad8"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeda1143ec45e3a3a51c169a6d7fc301519924ba"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "7ebaf501b0fbc88afdc8991217003bbf421d08ea52e838c38aca9f69ab0bc5f8"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b6cca6c8de4a329acf24de31f922ccd2ce228a"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "28da127379c640b77c934d93d4a56ea3d0f69a2031f22732ad22ca5f6aff80e2"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.aarch64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da521008272a7c0a457f161c03af7491fe6e700b"
os = "windows"

    [[Luna.download]]
    sha256 = "5c11e5c694465ddb6529c3c931f2991b16646e6edeeda312e22206998db34d53"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cd277d19ac1161f7af998790f93e99f61337f97"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "b546e16398c8b3ca152720a995eb92262ae6d20c32a74c35ec92886a7fe037a6"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bccd9515e1edb12b20d16e1d7b35e1e5e61f4efb"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "58d6c5b62cdc83c64bd4a27dd7d34f26d16dd7adb39390932d844547caf4e7f0"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b165c1b97c759371f0084bc877917bed9350b80"
os = "freebsd"

    [[Luna.download]]
    sha256 = "e8da6a77655f0e9231c92a811034cd5cb968e8d0af5035876c9c14f113a351fb"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85fbdfbfd88e7f9617415ec6d540230803586639"
os = "windows"

    [[Luna.download]]
    sha256 = "3c8aa28f0288a83fdf85fde82ab1f1e3ed19ce04e276ee24872b66f412370f9f"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afad82105e188ea3267dd040adea58cb156a4f51"
os = "windows"

    [[Luna.download]]
    sha256 = "cb9563c574ff1a3a37833dffb4394d672bb7b84b0de865d20c88b76df3de8d37"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.i686-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9612e4b0a35d3809197e94da7fe5542abc59af"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "98cfa5a4931254ebfb3860998135cf00fe2b86aaa7b4ab295fa9da7c7bf47d0a"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+0/Luna.v0.23.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
