[[Luna]]
arch = "aarch64"
git-tree-sha1 = "328aaf52d9156cc02c513cf67a63f9f2df9f86d6"
os = "macos"

    [[Luna.download]]
    sha256 = "614058f026478f1e34ba5dfa08d851c341d849de217a1fd0143096147efed3a7"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.aarch64-apple-darwin.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a99e9fa8d5476c1c3f2a38acda7f20e8f0c3f0c0"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "a644308b274d0206ffccd66a7b348c8b3e5f87b3f599b8bca8bed319f031aa48"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95651e3648d17ada03c7e921257e48add1c782f4"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "938aa6f44f84fb32527966076a1bc523151ecb0032de5c70334c0b281f9f4134"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47a8347a1bf02e801008827869efa6e89ebb735e"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "31ba1e3e9e2a46b540e4d2794a52720ba0c8991b845220d1f500456072a3c102"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.aarch64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84ad103891a01e4c5152dbd448974e7ac2daca03"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "417e3fe5ddebca62fb2efa14a42e02e7184901c31e490e0b2a04bca6ea0e3c09"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.aarch64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7b480012044fb83e1d7e81ba56d93250a8822b1"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "b646d0145ba4ca02e69c923d0ba159b6dd81825f9f1d45a44a335ef510325ebf"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9576867b0b5c96719e1cd7a10f115d7b5739d0b1"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "f41ab9fb2211b1ff895011753194b9733b4b070c17bcbec2779e68d17eefe5e2"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63199bc045215479dee312614ad1448c800fc463"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "52f2bf5846e0725bf47993e3a7b29fcca9c835c02150665976db397cabff6468"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f00f366ea3291262fbd9da404238b6c8bdf1b160"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "5f57e9a5ca00558bdf939cd0dee6b494a22d0c6310f53609ef31a6dced156abb"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a2f809b3420c483f857a9baa2e7189e0a3ab421"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "470e99aa5c9b7e9a8d3786a2ccd0e8740e9211894050b6c2b44ee2d2f9e85604"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c7dff81d23f0dc5643faea3c31154e60425f344"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "abfa19f53d6629151fbd50070e6701c2a0932a72b0f09647a9dd3c83ae832eb5"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f726177e4931ce63176f597c67fb808cf74fc885"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "9534efa558ec82461ae7268b1d096e50b191488784a683edb1b3392c189c08b3"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27609f75b3c615fe4e45c010750fbaf87319b80e"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "652b0918d912a7181f09077e4565f56a14541336667e21144bc0ac9ef98c2e63"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d509ef42a16e7614262cfbfc2c4065de3df19a36"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "e162f8ac35462cb481ed15f1d67daf8366ce53fc2b2f7dfcdfaef6a7e6a5fbb0"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b4fd817d4bc28ab27bd2211aa4b8527d18e05d2"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "e8c78ea43c0a6d8a7a57d907b69000d8cf97d84a0192f00526e8700bec96049c"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a2231cd38b0b6484b06da3450dcb1ef8ed53043"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "226b70e09a16cedb2a60a2422ad8267bae86a1bc8a6f948bfaca987be1ad6953"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f19640e795ab5fe193a23fe07f82a8d644dfa659"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "5fc426dabf1ba2ef08ff9b30ae7a627a6585eb3e645726631d3006aa22f92371"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6d1d4645d7a0e71b1ea9c8e1710dd31af5a2fe2"
os = "windows"

    [[Luna.download]]
    sha256 = "97fa49e75bf4893f3b3b72925b9f4362321b1b3991ab8f134cb919aef56ba071"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "206a1a426b545412cc5f6c9a483d824ba82dac6c"
os = "windows"

    [[Luna.download]]
    sha256 = "f37d75a2c60ef435ac043ce8c22dd7dc2a11c61272c07518eb23d63e5f6fd896"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.i686-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a565874696ade27b9ad760b00208f0e9aa57af9e"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "5f24aa438576278b8b5767f98505b170cc9844b6cb067b7ec4986c3e0b3debe7"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d3ce47707443e65b1d045c20b275d59d257b07d"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "045832248311843fb68e5af44b26719dd46f14e8bb3cdfd1a7331e00ba826f05"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
git-tree-sha1 = "8f5bbe8bda23231f7f75d0da21f6481b7dedfc3a"
os = "macos"

    [[Luna.download]]
    sha256 = "df92cda27627c112714ac18d504eac10b61db53d590e5b22bf9f8a8972f467a9"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-apple-darwin.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7b5f1c878ca3adab47c52d666477ceada167453"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "30a585e8577ebe4eb68503d0e4b2b03b0063e2e4c9c39457ee95d3a7f6b3c3fa"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2a1a4866f40c796efd5680cb672248bf10e82be"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "c012c500ff0eb28aea8bf1740f90df4a69697fb20a3e04edef7cf1f3b0fced1c"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6400ce45add547a4c061e50c6f55dfce73257b3"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "0804d782ca72b37a03da67c39d3ef6ec0b50bfab704dfbafb45105c259301cf1"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f111870a004f3206c98fd9f31bc725c7a93f08d1"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "3b490a0144615964a0edd19370638cb6f895c1f58f20085451cde7abd2f212ab"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
git-tree-sha1 = "77d976fbf0249cc83216c771e633a62e774bc0ac"
os = "freebsd"

    [[Luna.download]]
    sha256 = "78625bcbd4e4671cca683f840c0f218f61846e57bfead9530fcae382ea80f1b9"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-unknown-freebsd.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f075e2fe29bab18767f71ab7cb7787ebfa5b5d2"
os = "windows"

    [[Luna.download]]
    sha256 = "4dc63ba387e672966f875cbb1ba1a44a46d884426dc24bcfe5b5d8e20636e7a6"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c8b6b1ac403d4cdf771e215ea66490632add6c6"
os = "windows"

    [[Luna.download]]
    sha256 = "086ceed3309bf081924e9748977a225e8502158fe9f40386f978016ce1c283b6"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.26.2+0/Luna.v0.26.2.x86_64-w64-mingw32-cxx11.tar.gz"
