[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dee5ff65d3fa21c66be81144cf5555df815592cf"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "2b0e18ecf485ff60f36872bea6a0ac51851f8ecf9921314dfce8d1cb017aa751"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.aarch64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3402bc70c97c7637fbd16f1074005c96d3adffc6"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "74c2ea2af39471afc122e7c2da1e788b477d00c68050439747161d6f459e377f"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.aarch64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ec976fd04ea0b1571cef5ef08706eb5f1164581"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "0bbd338d1d139679ad0fe6c4f9a56c401f889923a7308760f371f798704d8b37"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ee1d6f0b0f39212d91cf69119f51597524978a2"
os = "windows"

    [[Luna.download]]
    sha256 = "c3739c1744273662e86dcf1b99693f45e5a96e23b7d62d562fdbc77c9ceb438f"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9cb0f99cd3a9954fe53c9110d44259f5f21a9d"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "4ea0ae300c127d88db8b010f3bf1bc5168ff96f36374713ff14025b8fb582a44"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b49a6a9659e471d91a2b821ba5d27d6380acd0ef"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "dfad2037098bdb37911515ff6b8a07d70083e62d957169dca0583043e0282113"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-linux-musl-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a57221c5e000b7f651acf438a28328516bc00019"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "f30ee968014112709f92b1c8b50063fc4f5107b86a54ff1505938a43b32b6388"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dfbfba6724a188f87b6acf5b786d10c4ce188a5"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "964024d933efef1a7b7ea63d483c7b2c272efa6440fa5ac25f77a71bb3933217"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b952768656ba106250118faa704cd461a24de915"
os = "macos"

    [[Luna.download]]
    sha256 = "a19d2b7306ba8c00f9704d818d3075ce22aa505672e56e4d56d2ac0ea006e34a"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e6aa00fbb36ef731e7184f1cfa5a3e65a049c78"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "974a9f9b54b7a9765da6e1a4e4305c9a4f085baabcecad7d9b88ebee050825be"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ccba34e9495c7648cbcd2a06d2f6bbcfa9f7455"
os = "windows"

    [[Luna.download]]
    sha256 = "60ecf38e159fecbad7de8834751f1b69c14d2654c032cffd28bf299b7a9d3787"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03dd50745fb2cab759526d2f08f66f691c362c33"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "f8d7961a4d2f923a88bdd27a1ee9ccfcbe4ec35986a19f6ba87801d2db691a66"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d51188469e7ab9d546c563ea79a51c18bf4ca4ed"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "e8304fb41e7f8c63be7b4f4d9746b87e330fa6fa126ebf95e4866fa1f74febce"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddcf8aa13841c2b62fd5115474634170864ec1df"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "8684e0d606d0363c13ff7d5d870a9d4ad2688190a981ff0e07f6dca0e49d780e"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798abfa4e8412d11b3bfe3739507fe92914257ac"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "16fd23d3d1289c06976958a78e32c033c6544f23e913ebc443bb8fb0237926a2"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-linux-musl-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3929d23a85f2e05ff71b7fad24dce44d510a8eff"
os = "macos"

    [[Luna.download]]
    sha256 = "89a46439fda4d1619cba09cb3fd1e4f70771113646d4ac06bd71394ddc70c11b"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea8cfe1aa5ee7dab89140f49cac3937d63adc370"
os = "freebsd"

    [[Luna.download]]
    sha256 = "5eecfee70be79d2973dcbe8790d3a919e29199397b6dd3e0cb3c86533de0d4e8"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Luna]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56fa1bd2b2d41619600e47c18df37e7f256480f4"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "87a761f1a54a258c72fdb31dac1af8649f0bd5ba923189d31152c59c5e84ffb3"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8edc4e74bd3e946c55db8668a31b9676405d18b6"
os = "windows"

    [[Luna.download]]
    sha256 = "762deb567c29f6a2c5949d8f25bd9a95ebd55318b3e4fb27f23e287d5e833094"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-w64-mingw32-cxx03.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "015bdba518e561de78f701433be246a7adf92bf9"
os = "windows"

    [[Luna.download]]
    sha256 = "e1e882eb6847e3018f0182c6de39db9a9f250fcb2c6bb234603b1cbfd46c538c"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-w64-mingw32-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8f6321b81337618037472a851013b4cb89a9237"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "917b0089de4861f10eef4bc55d2ebc5a93482e0873a51a12e607030903f1dcfb"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ffbc22c131b66c8c4f0b57cd7afd3be95bb1395"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "3b00ea121b04e8722f0fa28e53518d807544e3186ade015ab5dc6bd2d601a4d0"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Luna]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d30b83fe64cf68d052eb02e5572b01ae9477f8d"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "ab9919fd50a890d16bfa3330261fd1bf0d1ac8376893174993949f2b2fe76743"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Luna]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f0a37c4d137d1679c10aed929980454bd1494dc"
libc = "glibc"
os = "linux"

    [[Luna.download]]
    sha256 = "e487ba2d19522a477723504375593817d0791c3dafb41ff859ade216b26fdc96"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Luna]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38662bbf95cb7a44c54acb165006a236f99d5787"
os = "freebsd"

    [[Luna.download]]
    sha256 = "51bda3030c5bdace89c97e711e20cac0b642d49c94d3a77376854047db158197"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Luna]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8548a3db9800c95f62c4bea1ec28e8c419a0e59e"
libc = "musl"
os = "linux"

    [[Luna.download]]
    sha256 = "edc19fb170c5f75eb29a66abaa316def4f8a1d5e450034f45b06b8fc196bd6c9"
    url = "https://github.com/JuliaBinaryWrappers/Luna_jll.jl/releases/download/Luna-v0.23.0+1/Luna.v0.23.0.i686-linux-musl-cxx03.tar.gz"
